Update the whole repo

diff --git a/tests/run_examples b/tests/run_examples
--- a/tests/run_examples
+++ b/tests/run_examples
@@ -1,41 +1,31 @@
 #!/bin/sh
 
+if ! command -v sbcl --version 2>/dev/null 1>&2;
+then
+  echo "No SBCL on the system" >&2;
+  exit 1;
+fi
+
 if ! command -v node --version 2>/dev/null 1>&2;
 then
   echo "No Node.js on the system" >&2;
   exit 1;
 fi
 
-TEST_SCRIPT=examples/helloworld.lisp
-
-if ! command -v sbclrun cl2js.lisp "$TEST_SCRIPT" 2>/dev/null 1>&2;
-then
-  echo "No SBCL or its wrapper on the system" >&2;
-  exit 1;
-fi
-
-if ! command -v cclrun cl2js.lisp "$TEST_SCRIPT" 2>/dev/null 1>&2;
-then
-  echo "No Clozure CL or its wrapper on the system" >&2;
-  exit 1;
-fi
-
-if ! command -v abclrun cl2js.lisp "$TEST_SCRIPT" 2>/dev/null 1>&2;
-then
-  echo "No Armed Bear CL or its wrapper on the system" >&2;
-  exit 1;
-fi
+# Build `cl2js` with SBCL.
+./build
 
 CL2JS=./cl2js
 
-for lisp in sbcl ccl abcl;
+for script in examples/*;
 do
-  for script in examples/*;
-  do
-    echo "Test $script with $lisp ..."
-    $CL2JS "$lisp" "$script" | node >/dev/null || (
-      echo "Failed while testing $script with $lisp";
-      exit 1;
-    )
-  done
+  echo "Test $script ..."
+  $CL2JS "$script" | node >/dev/null || (
+    echo "Failed while testing $script with $lisp";
+    ./clean
+    exit 1;
+  )
 done
+
+# Clean local build
+./clean
